//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddOne.Framework.DAO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddOne.Framework.DAO.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added permission for addin {0} - Value: {1}.
        /// </summary>
        internal static string AddInPermission {
            get {
                return ResourceManager.GetString("AddInPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added permission for user {0} - addin {1} - Value: {2}.
        /// </summary>
        internal static string AddInUserPermission {
            get {
                return ResourceManager.GetString("AddInUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return type of method {1} of type {0} is not boolean.
        /// </summary>
        internal static string AuthorizationMessage {
            get {
                return ResourceManager.GetString("AuthorizationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type need to have boObjectType defined.
        /// </summary>
        internal static string DocumentObjectTypeInvalid {
            get {
                return ResourceManager.GetString("DocumentObjectTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL execution finished - {0}.
        /// </summary>
        internal static string EndExecuteStatement {
            get {
                return ResourceManager.GetString("EndExecuteStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed UpdateOrSave for {0}.
        /// </summary>
        internal static string EndUpdateOrSave {
            get {
                return ResourceManager.GetString("EndUpdateOrSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} {1} - {2}.
        /// </summary>
        internal static string ErrorAddingDI {
            get {
                return ResourceManager.GetString("ErrorAddingDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Statement error executing {0} - {1}.
        /// </summary>
        internal static string ErrorExecuteStatement {
            get {
                return ResourceManager.GetString("ErrorExecuteStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating {0} {1} - {2}.
        /// </summary>
        internal static string ErrorUpdatingDI {
            get {
                return ResourceManager.GetString("ErrorUpdatingDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing SQL {0}.
        /// </summary>
        internal static string ExecuteForListCommand {
            get {
                return ResourceManager.GetString("ExecuteForListCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added object {0} for ExecuteSqlForList return list object.
        /// </summary>
        internal static string ExecuteForListReturn {
            get {
                return ResourceManager.GetString("ExecuteForListReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object of type {0}. SQL object type is {1}.
        /// </summary>
        internal static string ExecuteForObjectArgument {
            get {
                return ResourceManager.GetString("ExecuteForObjectArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Select for Object error: {0}.
        /// </summary>
        internal static string ExecuteForObjectError {
            get {
                return ResourceManager.GetString("ExecuteForObjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returning object {0} for select statement {1}.
        /// </summary>
        internal static string ExecuteForObjectReturn {
            get {
                return ResourceManager.GetString("ExecuteForObjectReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading BOM for XML - {0}.
        /// </summary>
        internal static string GetBomFromXMLError {
            get {
                return ResourceManager.GetString("GetBomFromXMLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished execution of GetNextCode for {0}.
        /// </summary>
        internal static string GetNextCodeEnd {
            get {
                return ResourceManager.GetString("GetNextCodeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing executing of GetNextCode for {0}.
        /// </summary>
        internal static string GetNextCodeStart {
            get {
                return ResourceManager.GetString("GetNextCodeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing XML BOM - {0}.
        /// </summary>
        internal static string GetXMLBOMError {
            get {
                return ResourceManager.GetString("GetXMLBOMError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu processed.
        /// </summary>
        internal static string MenuEnd {
            get {
                return ResourceManager.GetString("MenuEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro processing Menu - {0}.
        /// </summary>
        internal static string MenuError {
            get {
                return ResourceManager.GetString("MenuError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Menu {0} - {1}.
        /// </summary>
        internal static string MenuProcess {
            get {
                return ResourceManager.GetString("MenuProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Menu XML.\n{0}.
        /// </summary>
        internal static string MenuStart {
            get {
                return ResourceManager.GetString("MenuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission processing ended for {0}.
        /// </summary>
        internal static string PermissionEnd {
            get {
                return ResourceManager.GetString("PermissionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding permission {0} - {1}.
        /// </summary>
        internal static string PermissionError {
            get {
                return ResourceManager.GetString("PermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting permission processing {0}.
        /// </summary>
        internal static string PermissionStart {
            get {
                return ResourceManager.GetString("PermissionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission {0} added.
        /// </summary>
        internal static string PermissionSuccess {
            get {
                return ResourceManager.GetString("PermissionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating permission {0} - {1}.
        /// </summary>
        internal static string PermissionUpdateError {
            get {
                return ResourceManager.GetString("PermissionUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission {0} updated.
        /// </summary>
        internal static string PermissionUpdateSuccess {
            get {
                return ResourceManager.GetString("PermissionUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error assigning property {0}.
        /// </summary>
        internal static string PrepareObjectError {
            get {
                return ResourceManager.GetString("PrepareObjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} has property {1} of type {2}. Statement object type is {3}..
        /// </summary>
        internal static string PrepareObjectInvalidParameter {
            get {
                return ResourceManager.GetString("PrepareObjectInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} does not have property {1}.
        /// </summary>
        internal static string PrepareObjectMissingParameter {
            get {
                return ResourceManager.GetString("PrepareObjectMissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} not supported.
        /// </summary>
        internal static string ProcessTupleError {
            get {
                return ResourceManager.GetString("ProcessTupleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting SQL statement - {0}.
        /// </summary>
        internal static string StartExecuteStatement {
            get {
                return ResourceManager.GetString("StartExecuteStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started UpdateOrSave for {0}.
        /// </summary>
        internal static string StartUpdateOrSave {
            get {
                return ResourceManager.GetString("StartUpdateOrSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} successfully added.
        /// </summary>
        internal static string SuccessAddindDI {
            get {
                return ResourceManager.GetString("SuccessAddindDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} successfully updated.
        /// </summary>
        internal static string SuccessUpdatingDI {
            get {
                return ResourceManager.GetString("SuccessUpdatingDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} executing UI-API XML - {1}.
        /// </summary>
        internal static string UIAPICodeAndError {
            get {
                return ResourceManager.GetString("UIAPICodeAndError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error executing UI-API XML - {0}.
        /// </summary>
        internal static string UIAPIError {
            get {
                return ResourceManager.GetString("UIAPIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update for {0} not necessary.
        /// </summary>
        internal static string UpdateDINotNecessary {
            get {
                return ResourceManager.GetString("UpdateDINotNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing permission - {0}.
        /// </summary>
        internal static string UpdateOrSavePermissionError {
            get {
                return ResourceManager.GetString("UpdateOrSavePermissionError", resourceCulture);
            }
        }
    }
}
