//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddOne.Framework.DAO {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddOne.Framework.DAO.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionando permissão para addin {0} - Valor: {1}.
        /// </summary>
        internal static string AddInPermission {
            get {
                return ResourceManager.GetString("AddInPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionando permissão para usuário {0} - addin {1} - Valor: {2}.
        /// </summary>
        internal static string AddInUserPermission {
            get {
                return ResourceManager.GetString("AddInUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retorno do metodo {1} de tipo {0} nao e booleano.
        /// </summary>
        internal static string AuthorizationMessage {
            get {
                return ResourceManager.GetString("AuthorizationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documents precisa ter boObjectType definido.
        /// </summary>
        internal static string DocumentObjectTypeInvalid {
            get {
                return ResourceManager.GetString("DocumentObjectTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizando execução de SQL - {0}.
        /// </summary>
        internal static string EndExecuteStatement {
            get {
                return ResourceManager.GetString("EndExecuteStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizado UpdateOrSave para {0}.
        /// </summary>
        internal static string EndUpdateOrSave {
            get {
                return ResourceManager.GetString("EndUpdateOrSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro adicionando {0} {1} - {2}.
        /// </summary>
        internal static string ErrorAddingDI {
            get {
                return ResourceManager.GetString("ErrorAddingDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro executando SQL {0} - {1}.
        /// </summary>
        internal static string ErrorExecuteStatement {
            get {
                return ResourceManager.GetString("ErrorExecuteStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro atualizando {0} {1} - {2}.
        /// </summary>
        internal static string ErrorUpdatingDI {
            get {
                return ResourceManager.GetString("ErrorUpdatingDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executando SQL {0}.
        /// </summary>
        internal static string ExecuteForListCommand {
            get {
                return ResourceManager.GetString("ExecuteForListCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionado objeto {0} ao retorno em ExecuteSqlForList.
        /// </summary>
        internal static string ExecuteForListReturn {
            get {
                return ResourceManager.GetString("ExecuteForListReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objeto do tipo {0}. Retorno da consulta no tipo {1}.
        /// </summary>
        internal static string ExecuteForObjectArgument {
            get {
                return ResourceManager.GetString("ExecuteForObjectArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro executando SQL: {0}.
        /// </summary>
        internal static string ExecuteForObjectError {
            get {
                return ResourceManager.GetString("ExecuteForObjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retornando objeto {0} em para consulta {1}.
        /// </summary>
        internal static string ExecuteForObjectReturn {
            get {
                return ResourceManager.GetString("ExecuteForObjectReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro lendo BOM do XML - {0}.
        /// </summary>
        internal static string GetBomFromXMLError {
            get {
                return ResourceManager.GetString("GetBomFromXMLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizada execução de GetNextCode para {0}.
        /// </summary>
        internal static string GetNextCodeEnd {
            get {
                return ResourceManager.GetString("GetNextCodeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando execução de GetNextCode para {0}.
        /// </summary>
        internal static string GetNextCodeStart {
            get {
                return ResourceManager.GetString("GetNextCodeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro processando XML BOM - {0}.
        /// </summary>
        internal static string GetXMLBOMError {
            get {
                return ResourceManager.GetString("GetXMLBOMError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Processado.
        /// </summary>
        internal static string MenuEnd {
            get {
                return ResourceManager.GetString("MenuEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro processando Menu - {0}.
        /// </summary>
        internal static string MenuError {
            get {
                return ResourceManager.GetString("MenuError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome {0} com formato i18n incorreto..
        /// </summary>
        internal static string MenuI18NFormatError {
            get {
                return ResourceManager.GetString("MenuI18NFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processando Menu {0} - {1}.
        /// </summary>
        internal static string MenuProcess {
            get {
                return ResourceManager.GetString("MenuProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processando XML de Menu.\n{0}.
        /// </summary>
        internal static string MenuStart {
            get {
                return ResourceManager.GetString("MenuStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizado processamento da permissão {0}.
        /// </summary>
        internal static string PermissionEnd {
            get {
                return ResourceManager.GetString("PermissionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro adicionando Permissão {0} - {1}.
        /// </summary>
        internal static string PermissionError {
            get {
                return ResourceManager.GetString("PermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando processamento da permissão {0}.
        /// </summary>
        internal static string PermissionStart {
            get {
                return ResourceManager.GetString("PermissionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão {0} adicionada.
        /// </summary>
        internal static string PermissionSuccess {
            get {
                return ResourceManager.GetString("PermissionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro atualizando Permissão {0} - {1}.
        /// </summary>
        internal static string PermissionUpdateError {
            get {
                return ResourceManager.GetString("PermissionUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissão {0} atualizada.
        /// </summary>
        internal static string PermissionUpdateSuccess {
            get {
                return ResourceManager.GetString("PermissionUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro setando propriedade {0}.
        /// </summary>
        internal static string PrepareObjectError {
            get {
                return ResourceManager.GetString("PrepareObjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objeto {0} tem propriedade {1} do tipo {2}. Retorno da consulta no tipo {3}..
        /// </summary>
        internal static string PrepareObjectInvalidParameter {
            get {
                return ResourceManager.GetString("PrepareObjectInvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objeto {0} não tem tem propriedade {1}.
        /// </summary>
        internal static string PrepareObjectMissingParameter {
            get {
                return ResourceManager.GetString("PrepareObjectMissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} nao suportado.
        /// </summary>
        internal static string ProcessTupleError {
            get {
                return ResourceManager.GetString("ProcessTupleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializando execução de SQL - {0}.
        /// </summary>
        internal static string StartExecuteStatement {
            get {
                return ResourceManager.GetString("StartExecuteStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando UpdateOrSave para {0}.
        /// </summary>
        internal static string StartUpdateOrSave {
            get {
                return ResourceManager.GetString("StartUpdateOrSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} adicionado com sucesso.
        /// </summary>
        internal static string SuccessAddindDI {
            get {
                return ResourceManager.GetString("SuccessAddindDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} atualizado com sucesso.
        /// </summary>
        internal static string SuccessUpdatingDI {
            get {
                return ResourceManager.GetString("SuccessUpdatingDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualização de {0} não necessária.
        /// </summary>
        internal static string UpdateDINotNecessary {
            get {
                return ResourceManager.GetString("UpdateDINotNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro processando Permissões - {0}.
        /// </summary>
        internal static string UpdateOrSavePermissionError {
            get {
                return ResourceManager.GetString("UpdateOrSavePermissionError", resourceCulture);
            }
        }
    }
}
