//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dover.Framework.Form {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dover.Framework.Form.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading addin to separate AppDomain for validation.
        /// </summary>
        internal static string AdminCreatingAppDomain {
            get {
                return ResourceManager.GetString("AdminCreatingAppDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database structure will be modified.
        /// </summary>
        internal static string AdminDatabaseChangeWarning {
            get {
                return ResourceManager.GetString("AdminDatabaseChangeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file.
        /// </summary>
        internal static string AdminEmptyFile {
            get {
                return ResourceManager.GetString("AdminEmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string AdminInstall {
            get {
                return ResourceManager.GetString("AdminInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        internal static string AdminInstalled {
            get {
                return ResourceManager.GetString("AdminInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install/Update.
        /// </summary>
        internal static string AdminInstallUpdate {
            get {
                return ResourceManager.GetString("AdminInstallUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid addin.
        /// </summary>
        internal static string AdminInvalidAddin {
            get {
                return ResourceManager.GetString("AdminInvalidAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Management.
        /// </summary>
        internal static string AdminManagement {
            get {
                return ResourceManager.GetString("AdminManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module configuration and installation.
        /// </summary>
        internal static string AdminMenu {
            get {
                return ResourceManager.GetString("AdminMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addin File.
        /// </summary>
        internal static string AdminModuleFile {
            get {
                return ResourceManager.GetString("AdminModuleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules file.
        /// </summary>
        internal static string AdminModuleFilterPrefix {
            get {
                return ResourceManager.GetString("AdminModuleFilterPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string AdminModuleHistory {
            get {
                return ResourceManager.GetString("AdminModuleHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AdminModuleName {
            get {
                return ResourceManager.GetString("AdminModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string AdminModuleType {
            get {
                return ResourceManager.GetString("AdminModuleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string AdminModuleVersion {
            get {
                return ResourceManager.GetString("AdminModuleVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AdminOK {
            get {
                return ResourceManager.GetString("AdminOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string AdminRemove {
            get {
                return ResourceManager.GetString("AdminRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string AdminRunning {
            get {
                return ResourceManager.GetString("AdminRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string AdminShutdown {
            get {
                return ResourceManager.GetString("AdminShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string AdminStart {
            get {
                return ResourceManager.GetString("AdminStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string AdminStatus {
            get {
                return ResourceManager.GetString("AdminStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string AdminStopped {
            get {
                return ResourceManager.GetString("AdminStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully installed addin.
        /// </summary>
        internal static string AdminSuccessInstall {
            get {
                return ResourceManager.GetString("AdminSuccessInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules Management.
        /// </summary>
        internal static string AdminTitle {
            get {
                return ResourceManager.GetString("AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All arguments are mandatory.
        /// </summary>
        internal static string AllArgumentsMandatory {
            get {
                return ResourceManager.GetString("AllArgumentsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ExportDBInfoButtonCancel {
            get {
                return ResourceManager.GetString("ExportDBInfoButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ExportDBInfoButtonOK {
            get {
                return ResourceManager.GetString("ExportDBInfoButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string ExportDBInfoCode {
            get {
                return ResourceManager.GetString("ExportDBInfoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create file.
        /// </summary>
        internal static string ExportDBInfoFileNotFound {
            get {
                return ResourceManager.GetString("ExportDBInfoFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select object type.
        /// </summary>
        internal static string ExportDBInfoLabelSelectSource {
            get {
                return ResourceManager.GetString("ExportDBInfoLabelSelectSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export DB information.
        /// </summary>
        internal static string ExportDBInfoMenu {
            get {
                return ResourceManager.GetString("ExportDBInfoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ExportDBInfoName {
            get {
                return ResourceManager.GetString("ExportDBInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File exported successfully.
        /// </summary>
        internal static string ExportDBInfoSuccess {
            get {
                return ResourceManager.GetString("ExportDBInfoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Database Information.
        /// </summary>
        internal static string ExportDBInfoTitle {
            get {
                return ResourceManager.GetString("ExportDBInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Field.
        /// </summary>
        internal static string ExportDBInfoUDF {
            get {
                return ResourceManager.GetString("ExportDBInfoUDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Object.
        /// </summary>
        internal static string ExportDBInfoUDO {
            get {
                return ResourceManager.GetString("ExportDBInfoUDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Table.
        /// </summary>
        internal static string ExportDBInfoUDT {
            get {
                return ResourceManager.GetString("ExportDBInfoUDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please inform a file name.
        /// </summary>
        internal static string FileDialogTitle {
            get {
                return ResourceManager.GetString("FileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder.
        /// </summary>
        internal static string FolderDialogTitle {
            get {
                return ResourceManager.GetString("FolderDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string MngmntActive {
            get {
                return ResourceManager.GetString("MngmntActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string MngmntDefault {
            get {
                return ResourceManager.GetString("MngmntDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string MngmntDescription {
            get {
                return ResourceManager.GetString("MngmntDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string MngmntGeneral {
            get {
                return ResourceManager.GetString("MngmntGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string MngmntInactive {
            get {
                return ResourceManager.GetString("MngmntInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addin startup configuration.
        /// </summary>
        internal static string MngmntMenu {
            get {
                return ResourceManager.GetString("MngmntMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string MngmntName {
            get {
                return ResourceManager.GetString("MngmntName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per User.
        /// </summary>
        internal static string MngmntPerUser {
            get {
                return ResourceManager.GetString("MngmntPerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string MngmntStatus {
            get {
                return ResourceManager.GetString("MngmntStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addin startup configuration.
        /// </summary>
        internal static string MngmntTitle {
            get {
                return ResourceManager.GetString("MngmntTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string MngmntUser {
            get {
                return ResourceManager.GetString("MngmntUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string MngmntVersion {
            get {
                return ResourceManager.GetString("MngmntVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
