//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddOne.Framework.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddOne.Framework.Service.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum Assembly de nome {0} encontrado.
        /// </summary>
        internal static string AddInNotFound {
            get {
                return ResourceManager.GetString("AddInNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1S resource para {0} nao configurado.
        /// </summary>
        internal static string B1SResourceMissing {
            get {
                return ResourceManager.GetString("B1SResourceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checando MD5Sum({0}) - para {1}.
        /// </summary>
        internal static string CheckSum {
            get {
                return ResourceManager.GetString("CheckSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializando configuração do AddIn {0}.
        /// </summary>
        internal static string ConfiguringAddin {
            get {
                return ResourceManager.GetString("ConfiguringAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro reiniciando addins.
        /// </summary>
        internal static string ErrorReboot {
            get {
                return ResourceManager.GetString("ErrorReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro atualizando AddOne, em troca de base de dados..
        /// </summary>
        internal static string EventCompanyChangedError {
            get {
                return ResourceManager.GetString("EventCompanyChangedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro atualizando AddOne. Evento de troca de idioma..
        /// </summary>
        internal static string EventLanguageChangedError {
            get {
                return ResourceManager.GetString("EventLanguageChangedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro atualizando arquivo {0} - Versao {1}..
        /// </summary>
        internal static string FileError {
            get {
                return ResourceManager.GetString("FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo {0} - Versao {1} - não encontrado.
        /// </summary>
        internal static string FileMissing {
            get {
                return ResourceManager.GetString("FileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizado arquivo {0} - Versao {1}.
        /// </summary>
        internal static string FileUpdated {
            get {
                return ResourceManager.GetString("FileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignorando arquivo {0} - não encontrado.
        /// </summary>
        internal static string IgnoringFile {
            get {
                return ResourceManager.GetString("IgnoringFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licença inválida.
        /// </summary>
        internal static string InvalidLicense {
            get {
                return ResourceManager.GetString("InvalidLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo {0} não encontrado.
        /// </summary>
        internal static string LicenseFileMissing {
            get {
                return ResourceManager.GetString("LicenseFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5Sum: {0}.
        /// </summary>
        internal static string MD5Sum {
            get {
                return ResourceManager.GetString("MD5Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro processando evento para menu {0} - {1}.
        /// </summary>
        internal static string MenuDispatchError {
            get {
                return ResourceManager.GetString("MenuDispatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processando evento do tipo {0} para classe/metodo {1}.
        /// </summary>
        internal static string MenuDispatchInfo {
            get {
                return ResourceManager.GetString("MenuDispatchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processando atributo {0} - classe {1}.
        /// </summary>
        internal static string ProcessingAttribute {
            get {
                return ResourceManager.GetString("ProcessingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly {0} registrado no container.
        /// </summary>
        internal static string RegisteredAssembly {
            get {
                return ResourceManager.GetString("RegisteredAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrando assembly {0} no container.
        /// </summary>
        internal static string RegisteringAssembly {
            get {
                return ResourceManager.GetString("RegisteringAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrando menu {0} - para tipo {1}.
        /// </summary>
        internal static string RegisteringMenuEvent {
            get {
                return ResourceManager.GetString("RegisteringMenuEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reiniciando AddOne.
        /// </summary>
        internal static string Restarting {
            get {
                return ResourceManager.GetString("Restarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro salvando addin {0}.
        /// </summary>
        internal static string SaveAddInError {
            get {
                return ResourceManager.GetString("SaveAddInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddIn {0} salvo com sucesso.
        /// </summary>
        internal static string SaveAddInSuccess {
            get {
                return ResourceManager.GetString("SaveAddInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro inicializando addin.
        /// </summary>
        internal static string StartThisError {
            get {
                return ResourceManager.GetString("StartThisError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro inesperado em CryptoService.
        /// </summary>
        internal static string UnhandledCrypto {
            get {
                return ResourceManager.GetString("UnhandledCrypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro inesperado iniciando serviço de licença.
        /// </summary>
        internal static string UnhandledLicense {
            get {
                return ResourceManager.GetString("UnhandledLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando atualização de assemblies - {0}.
        /// </summary>
        internal static string UpdatingAssembly {
            get {
                return ResourceManager.GetString("UpdatingAssembly", resourceCulture);
            }
        }
    }
}
