//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dover.Framework.Service {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dover.Framework.Service.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assembly named {0} found.
        /// </summary>
        internal static string AddInNotFound {
            get {
                return ResourceManager.GetString("AddInNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag for form {1} not found on assembly {0}.
        /// </summary>
        internal static string B1SResourceKeyNotFound {
            get {
                return ResourceManager.GetString("B1SResourceKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B1S resource for {0} not found.
        /// </summary>
        internal static string B1SResourceMissing {
            get {
                return ResourceManager.GetString("B1SResourceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag VSICreated not found on assembly {0}.
        /// </summary>
        internal static string B1SResourceVSICreatedNotFound {
            get {
                return ResourceManager.GetString("B1SResourceVSICreatedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking MD5Sum({0}) - for {1}.
        /// </summary>
        internal static string CheckSum {
            get {
                return ResourceManager.GetString("CheckSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully configured addin {0}.
        /// </summary>
        internal static string ConfiguredAddin {
            get {
                return ResourceManager.GetString("ConfiguredAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring Menu for {0}.
        /// </summary>
        internal static string ConfigureMenu {
            get {
                return ResourceManager.GetString("ConfigureMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing AddIn configuration {0}.
        /// </summary>
        internal static string ConfiguringAddin {
            get {
                return ResourceManager.GetString("ConfiguringAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error restarting addin.
        /// </summary>
        internal static string ErrorReboot {
            get {
                return ResourceManager.GetString("ErrorReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating Dover in company update event.
        /// </summary>
        internal static string EventCompanyChangedError {
            get {
                return ResourceManager.GetString("EventCompanyChangedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating Dover in language change event.
        /// </summary>
        internal static string EventLanguageChangedError {
            get {
                return ResourceManager.GetString("EventLanguageChangedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating file {0} - Version {1}..
        /// </summary>
        internal static string FileError {
            get {
                return ResourceManager.GetString("FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} - Version {1} - not found.
        /// </summary>
        internal static string FileMissing {
            get {
                return ResourceManager.GetString("FileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated file {0} - Version {1}.
        /// </summary>
        internal static string FileUpdated {
            get {
                return ResourceManager.GetString("FileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating file {0} - Version {1}.
        /// </summary>
        internal static string FileUpdating {
            get {
                return ResourceManager.GetString("FileUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormType {0} is not unique. It&apos;s not possible to register UI events..
        /// </summary>
        internal static string FormTypeNotUnique {
            get {
                return ResourceManager.GetString("FormTypeNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted Search.
        /// </summary>
        internal static string FS {
            get {
                return ResourceManager.GetString("FS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource {0} found.
        /// </summary>
        internal static string GetLocalizedStringFoundResource {
            get {
                return ResourceManager.GetString("GetLocalizedStringFoundResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource {0} not found.
        /// </summary>
        internal static string GetLocalizedStringNotFoundResource {
            get {
                return ResourceManager.GetString("GetLocalizedStringNotFoundResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} name with incorrect i18n format..
        /// </summary>
        internal static string i18nError {
            get {
                return ResourceManager.GetString("i18nError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring file {0} - not found..
        /// </summary>
        internal static string IgnoringFile {
            get {
                return ResourceManager.GetString("IgnoringFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring type on menu and form loading because of missing dependency..
        /// </summary>
        internal static string IgnoringType {
            get {
                return ResourceManager.GetString("IgnoringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource {0} not found on assembly..
        /// </summary>
        internal static string InternalResourceMissing {
            get {
                return ResourceManager.GetString("InternalResourceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid addin extension.
        /// </summary>
        internal static string InvalidAddInExtension {
            get {
                return ResourceManager.GetString("InvalidAddInExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid license..
        /// </summary>
        internal static string InvalidLicense {
            get {
                return ResourceManager.GetString("InvalidLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addin {0} not found during license load..
        /// </summary>
        internal static string LicenseAddInNotFound {
            get {
                return ResourceManager.GetString("LicenseAddInNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} not found.
        /// </summary>
        internal static string LicenseFileMissing {
            get {
                return ResourceManager.GetString("LicenseFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5Sum: {0}.
        /// </summary>
        internal static string MD5Sum {
            get {
                return ResourceManager.GetString("MD5Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing event for menu {0} - {1}.
        /// </summary>
        internal static string MenuDispatchError {
            get {
                return ResourceManager.GetString("MenuDispatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing event of type {0} for class/method {1}.
        /// </summary>
        internal static string MenuDispatchInfo {
            get {
                return ResourceManager.GetString("MenuDispatchInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing attribute {0} - class {1}.
        /// </summary>
        internal static string ProcessingAttribute {
            get {
                return ResourceManager.GetString("ProcessingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Category.
        /// </summary>
        internal static string QC {
            get {
                return ResourceManager.GetString("QC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebooting Dover Framework..
        /// </summary>
        internal static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly {0} registered in container.
        /// </summary>
        internal static string RegisteredAssembly {
            get {
                return ResourceManager.GetString("RegisteredAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering assembly {0} on container.
        /// </summary>
        internal static string RegisteringAssembly {
            get {
                return ResourceManager.GetString("RegisteringAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering menu {0} - for type {1}.
        /// </summary>
        internal static string RegisteringMenuEvent {
            get {
                return ResourceManager.GetString("RegisteringMenuEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addin {0} successfully removed.
        /// </summary>
        internal static string RemoveAddinSuccess {
            get {
                return ResourceManager.GetString("RemoveAddinSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource {1} not found for asm {0}.
        /// </summary>
        internal static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting Dover.
        /// </summary>
        internal static string Restarting {
            get {
                return ResourceManager.GetString("Restarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving addin {0}.
        /// </summary>
        internal static string SaveAddInError {
            get {
                return ResourceManager.GetString("SaveAddInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddIn {0} successfully saved.
        /// </summary>
        internal static string SaveAddInSuccess {
            get {
                return ResourceManager.GetString("SaveAddInSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License successfully saved.
        /// </summary>
        internal static string SaveLicenseSuccess {
            get {
                return ResourceManager.GetString("SaveLicenseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerTermination Error.
        /// </summary>
        internal static string ServerTerminationError {
            get {
                return ResourceManager.GetString("ServerTerminationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down Dover.
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down AddIn {0}.
        /// </summary>
        internal static string ShutdownAddin {
            get {
                return ResourceManager.GetString("ShutdownAddin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown Error.
        /// </summary>
        internal static string ShutdownError {
            get {
                return ResourceManager.GetString("ShutdownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing addin {0}.
        /// </summary>
        internal static string StartThisError {
            get {
                return ResourceManager.GetString("StartThisError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDO.
        /// </summary>
        internal static string UDO {
            get {
                return ResourceManager.GetString("UDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error in CryptoService.
        /// </summary>
        internal static string UnhandledCrypto {
            get {
                return ResourceManager.GetString("UnhandledCrypto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error initializing license service.
        /// </summary>
        internal static string UnhandledLicense {
            get {
                return ResourceManager.GetString("UnhandledLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addin with unsupported Framework, please update.
        /// </summary>
        internal static string UpdateFrameworkError {
            get {
                return ResourceManager.GetString("UpdateFrameworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating assemblies - {0}.
        /// </summary>
        internal static string UpdatingAssembly {
            get {
                return ResourceManager.GetString("UpdatingAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Query.
        /// </summary>
        internal static string UQ {
            get {
                return ResourceManager.GetString("UQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Field.
        /// </summary>
        internal static string UserField {
            get {
                return ResourceManager.GetString("UserField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Table.
        /// </summary>
        internal static string UserTable {
            get {
                return ResourceManager.GetString("UserTable", resourceCulture);
            }
        }
    }
}
