using System.Xml.Serialization;
using AddOne.Framework.Monad;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 

namespace AddOne.Framework.Model.SAP
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "BOM", Namespace = "", IsNullable = false)]
    public partial class FormattedSearchBOM : IBOM
    {
        private FormattedSearchBOMBO[] boField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BO")]
        public FormattedSearchBOMBO[] BO
        {
            get
            {
                return this.boField;
            }
            set
            {
                this.boField = value;
            }
        }

        internal override string[] GetKey()
        {
            return new string[]{"Index"};
        }

        internal override SAPbobsCOM.BoObjectTypes GetBOType()
        {
            return SAPbobsCOM.BoObjectTypes.oFormattedSearches;
        }

        internal override string GetName()
        {
            return Messages.FormattedSearch;
        }

        internal override System.Type GetBOClassType()
        {
            return typeof(SAPbobsCOM.IFormattedSearches);
        }

        internal override string GetFormatName(int i)
        {
            return "[" +
                boField.With(x => x[i])
                    .With(x => x.FormattedSearches)
                    .With(x => x[0])
                    .Return(x => x.FormID, string.Empty)
                + "].[" +
                boField.With(x => x[i])
                    .With(x => x.FormattedSearches)
                    .With(x => x[0])
                    .Return(x => x.ItemID, string.Empty);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class FormattedSearchBOMBO
    {

        private BOMBOAdmInfo admInfoField;

        private BOMBOQueryParams queryParamsField;

        private FormattedSearchField[] formattedSearchesField;

        private FormattedSearchValidValues[] userValidValuesField;

        /// <remarks/>
        public BOMBOAdmInfo AdmInfo
        {
            get
            {
                return this.admInfoField;
            }
            set
            {
                this.admInfoField = value;
            }
        }

        /// <remarks/>
        public BOMBOQueryParams QueryParams
        {
            get
            {
                return this.queryParamsField;
            }
            set
            {
                this.queryParamsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("row", IsNullable = false)]
        public FormattedSearchField[] FormattedSearches
        {
            get
            {
                return this.formattedSearchesField;
            }
            set
            {
                this.formattedSearchesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("row", IsNullable = false)]
        public FormattedSearchValidValues[] UserValidValues
        {
            get
            {
                return this.userValidValuesField;
            }
            set
            {
                this.userValidValuesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class FormattedSearchField
    {

        private string formIDField;

        private string itemIDField;

        private string columnIDField;

        private string actionField;

        private long queryIDField;

        private bool queryIDFieldSpecified;

        private string refreshField;

        private string fieldIDField;

        private string forceRefreshField;

        private string byFieldField;

        /// <remarks/>
        public string FormID
        {
            get
            {
                return this.formIDField;
            }
            set
            {
                this.formIDField = value;
            }
        }

        /// <remarks/>
        public string ItemID
        {
            get
            {
                return this.itemIDField;
            }
            set
            {
                this.itemIDField = value;
            }
        }

        /// <remarks/>
        public string ColumnID
        {
            get
            {
                return this.columnIDField;
            }
            set
            {
                this.columnIDField = value;
            }
        }

        /// <remarks/>
        public string Action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        public long QueryID
        {
            get
            {
                return this.queryIDField;
            }
            set
            {
                this.queryIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QueryIDSpecified
        {
            get
            {
                return this.queryIDFieldSpecified;
            }
            set
            {
                this.queryIDFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string Refresh
        {
            get
            {
                return this.refreshField;
            }
            set
            {
                this.refreshField = value;
            }
        }

        /// <remarks/>
        public string FieldID
        {
            get
            {
                return this.fieldIDField;
            }
            set
            {
                this.fieldIDField = value;
            }
        }

        /// <remarks/>
        public string ForceRefresh
        {
            get
            {
                return this.forceRefreshField;
            }
            set
            {
                this.forceRefreshField = value;
            }
        }

        /// <remarks/>
        public string ByField
        {
            get
            {
                return this.byFieldField;
            }
            set
            {
                this.byFieldField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class FormattedSearchValidValues
    {

        private string fieldValueField;

        /// <remarks/>
        public string FieldValue
        {
            get
            {
                return this.fieldValueField;
            }
            set
            {
                this.fieldValueField = value;
            }
        }
    }
}