//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dover.Framework.Model.SAP {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dover.Framework.Model.SAP.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string DefaultDocument {
            get {
                return ResourceManager.GetString("DefaultDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted Search.
        /// </summary>
        internal static string FormattedSearch {
            get {
                return ResourceManager.GetString("FormattedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Note.
        /// </summary>
        internal static string oCreditNotes {
            get {
                return ResourceManager.GetString("oCreditNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Note.
        /// </summary>
        internal static string oDeliveryNotes {
            get {
                return ResourceManager.GetString("oDeliveryNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory General Entry.
        /// </summary>
        internal static string oInventoryGenEntry {
            get {
                return ResourceManager.GetString("oInventoryGenEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory General Exit.
        /// </summary>
        internal static string oInventoryGenExit {
            get {
                return ResourceManager.GetString("oInventoryGenExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Invoice.
        /// </summary>
        internal static string oInvoices {
            get {
                return ResourceManager.GetString("oInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order.
        /// </summary>
        internal static string oOrders {
            get {
                return ResourceManager.GetString("oOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Credit Note.
        /// </summary>
        internal static string oPurchaseCreditNotes {
            get {
                return ResourceManager.GetString("oPurchaseCreditNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Delivery Note.
        /// </summary>
        internal static string oPurchaseDelivertNotes {
            get {
                return ResourceManager.GetString("oPurchaseDelivertNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Invoice.
        /// </summary>
        internal static string oPurchaseInvoices {
            get {
                return ResourceManager.GetString("oPurchaseInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        internal static string oPurchaseOrders {
            get {
                return ResourceManager.GetString("oPurchaseOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Return.
        /// </summary>
        internal static string oPurchaseReturns {
            get {
                return ResourceManager.GetString("oPurchaseReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Quotation.
        /// </summary>
        internal static string oQuotations {
            get {
                return ResourceManager.GetString("oQuotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Return.
        /// </summary>
        internal static string oReturns {
            get {
                return ResourceManager.GetString("oReturns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Category.
        /// </summary>
        internal static string QueryCategory {
            get {
                return ResourceManager.GetString("QueryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Field.
        /// </summary>
        internal static string UDF {
            get {
                return ResourceManager.GetString("UDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UDO.
        /// </summary>
        internal static string UDO {
            get {
                return ResourceManager.GetString("UDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Table.
        /// </summary>
        internal static string UDT {
            get {
                return ResourceManager.GetString("UDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Query.
        /// </summary>
        internal static string UserQuery {
            get {
                return ResourceManager.GetString("UserQuery", resourceCulture);
            }
        }
    }
}
